import { writeFileSync } from 'fs';
import { dirname } from 'path';
import { mkdirSync, existsSync } from 'fs';
import type { CDPManager } from '../cdp.js';
import type { ApiResponse, NetworkRequest } from '../../shared/types.js';
import { ErrorCode } from '../../shared/types.js';

const STRIPPED_HEADERS = new Set([
  'cookie',
  'authorization',
  // sec-fetch-* and host are managed by the browser automatically
  'host',
  'connection',
  'content-length',
]);

function isStripped(name: string): boolean {
  const lower = name.toLowerCase();
  if (lower.startsWith(':')) return true; // HTTP/2 pseudo-headers
  if (lower.startsWith('sec-')) return true;
  return STRIPPED_HEADERS.has(lower);
}

/**
 * Collect the headers we stripped, organized per request index. Used to emit
 * a STRIPPED_HEADERS block so users can see exactly what was removed and
 * re-add anything the server actually requires (e.g. SPA bearer tokens).
 */
function normalizePatternsLocal(input: string | string[] | undefined): string[] {
  if (!input) return [];
  const list = Array.isArray(input) ? input : [input];
  const out: string[] = [];
  for (const p of list) {
    if (!p) continue;
    for (const piece of String(p).split(',')) {
      const t = piece.trim();
      if (t) out.push(t);
    }
  }
  return out;
}

function collectStripped(requests: NetworkRequest[]): Array<Record<string, string>> {
  return requests.map((r) => {
    const out: Record<string, string> = {};
    if (!r.requestHeaders) return out;
    for (const [k, v] of Object.entries(r.requestHeaders)) {
      if (isStripped(k)) out[k] = v;
    }
    return out;
  });
}

function jsEscapeKey(k: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$\-]*$/.test(k) && !k.includes('-')
    ? k
    : JSON.stringify(k);
}

function formatHeaders(headers: Record<string, string> | undefined): string | null {
  if (!headers) return null;
  const kept: Array<[string, string]> = [];
  for (const [k, v] of Object.entries(headers)) {
    if (isStripped(k)) continue;
    kept.push([k, v]);
  }
  if (kept.length === 0) return null;
  const lines = kept.map(([k, v]) => `      ${jsEscapeKey(k)}: ${JSON.stringify(v)}`);
  return `{\n${lines.join(',\n')}\n    }`;
}

function formatBody(body: string | undefined): string | null {
  if (!body) return null;
  // If it looks like JSON, pretty-format as a JS string for readability
  const trimmed = body.trim();
  if ((trimmed.startsWith('{') && trimmed.endsWith('}')) || (trimmed.startsWith('[') && trimmed.endsWith(']'))) {
    try {
      JSON.parse(trimmed);
      // It's valid JSON — keep as-is but escape for JS string
      return JSON.stringify(trimmed);
    } catch {
      // not JSON, fall through
    }
  }
  return JSON.stringify(body);
}

function generateFetchCall(req: NetworkRequest, idx: number): string {
  const headersBlock = formatHeaders(req.requestHeaders);
  const bodyExpr = formatBody(req.requestBody);
  const method = (req.method || 'GET').toUpperCase();

  const opts: string[] = [`      method: ${JSON.stringify(method)}`];
  opts.push(`      credentials: 'include'`);
  if (headersBlock) opts.push(`      headers: ${headersBlock}`);
  if (bodyExpr) opts.push(`      body: ${bodyExpr}`);

  const optsBlock = `{\n${opts.join(',\n')}\n    }`;

  const statusComment = req.status ? ` // ${method} -> ${req.status}, ${req.size}B, ${req.duration}ms` : '';

  return `  // [${idx}] captured request${statusComment}
  {
    const res = await fetch(${JSON.stringify(req.url)}, ${optsBlock});
    const data = await res.text();
    log(${JSON.stringify(`[${idx}] ${method} ${req.url}`)}, '->', res.status, data.length, 'bytes');
    results.push({ idx: ${idx}, status: res.status, url: ${JSON.stringify(req.url)}, body: data });
  }`;
}

function buildScript(matches: NetworkRequest[], pattern: string | undefined): string {
  const stripped = collectStripped(matches);
  const hasAnyStripped = stripped.some((s) => Object.keys(s).length > 0);
  const hasAuth = stripped.some((s) => Object.keys(s).some((k) => k.toLowerCase() === 'authorization'));

  const header = [
    `// Generated by brw script gen on ${new Date().toISOString()}`,
    pattern ? `// URL pattern: ${pattern}` : '// All captured requests',
    `// Matched ${matches.length} request(s).`,
    `//`,
    `// Run: brw script run <this-file> [--param key=value]`,
    `// Globals available: args, log(...), sleep(ms). Use 'return <value>' to send a result.`,
    `// (The 'results' array below is returned by default.)`,
    `//`,
    `// ─── Auth handling ───────────────────────────────────────────────────────`,
    `// Cookies attach automatically via credentials: 'include'. Most cookie-based`,
    `// sites (LinkedIn, Google) work out of the box. Some SPAs (Whoop, X/Twitter)`,
    `// also need an explicit Authorization header that the page's JS reads from`,
    `// a non-httpOnly cookie or localStorage and adds at fetch time. If a request`,
    `// 401s/403s, look at STRIPPED_HEADERS below and re-add the header at runtime`,
    `// (read the cookie via document.cookie or storage at script time, not by`,
    `// pasting the captured token — it goes stale).`,
    ...(hasAuth ? [
      `//`,
      `// HEADS-UP: captured request(s) included an Authorization header. The browser`,
      `// will NOT re-send it for you. Re-add at runtime, e.g.:`,
      `//   const t = document.cookie.match(/<cookie-name>=([^;]+)/)?.[1];`,
      `//   const t = JSON.parse(localStorage.getItem('<key>')).token;`,
      `//   then merge into headers: { authorization: '...' + t, ... }`,
    ] : []),
    `// ─────────────────────────────────────────────────────────────────────────`,
    '',
  ].join('\n');

  // Emit a STRIPPED_HEADERS reference block (commented) so users can see what was removed.
  const strippedBlock = hasAnyStripped ? buildStrippedBlock(matches, stripped) : '';

  const body = matches.length === 0
    ? `      // No matching requests captured. Try interacting with the page first,\n      // then re-run: brw script gen --url-pattern <pattern>`
    : matches.map((req, i) => generateFetchCall(req, i)).join('\n\n');

  return `${header}${strippedBlock}
const results = [];

${body}

return results;
`;
}

function buildStrippedBlock(matches: NetworkRequest[], stripped: Array<Record<string, string>>): string {
  const lines: string[] = [
    `/* ── STRIPPED_HEADERS (reference; the generator removed these) ──────────`,
    ` *`,
    ` * The browser auto-attaches Cookie. The rest are listed for diagnosis only.`,
    ` * Re-read tokens from cookies/storage at runtime — do NOT paste captured`,
    ` * values into fetch headers, they expire.`,
    ` *`,
  ];
  for (let i = 0; i < matches.length; i++) {
    const s = stripped[i];
    const keys = Object.keys(s);
    if (keys.length === 0) continue;
    lines.push(` * [${i}] ${matches[i].method} ${matches[i].url.substring(0, 100)}${matches[i].url.length > 100 ? '…' : ''}`);
    for (const k of keys) {
      const v = s[k];
      const preview = v.length > 120 ? v.substring(0, 117) + '...' : v;
      lines.push(` *     ${k}: ${preview}`);
    }
  }
  lines.push(` */`, '');
  return lines.join('\n');
}

export async function handleScriptGen(
  cdp: CDPManager,
  params: {
    tab?: string;
    urlPattern?: string | string[];
    methods?: string[]; // filter by HTTP method (GET, POST, ...)
    statusMin?: number;
    limit?: number;
    output?: string; // path to write to
  }
): Promise<ApiResponse> {
  const tabId = params.tab;
  let requests = cdp.getNetworkBuffer(tabId);

  const patterns = normalizePatternsLocal(params.urlPattern);
  if (patterns.length > 0) {
    requests = requests.filter((r) => patterns.some((p) => r.url.includes(p)));
  }

  if (params.methods && params.methods.length > 0) {
    const wanted = new Set(params.methods.map((m) => m.toUpperCase()));
    requests = requests.filter((r) => wanted.has((r.method || 'GET').toUpperCase()));
  }

  if (typeof params.statusMin === 'number') {
    requests = requests.filter((r) => r.status >= params.statusMin!);
  }

  if (params.limit && params.limit > 0) {
    requests = requests.slice(-params.limit);
  }

  const source = buildScript(requests, patterns.length > 0 ? patterns.join(', ') : undefined);

  let writtenPath: string | null = null;
  if (params.output) {
    try {
      const dir = dirname(params.output);
      if (dir && !existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }
      writeFileSync(params.output, source, 'utf-8');
      writtenPath = params.output;
    } catch (err: any) {
      return {
        ok: false,
        error: `Failed to write script: ${err?.message || 'unknown'}`,
        code: ErrorCode.FILE_NOT_FOUND,
      };
    }
  }

  return {
    ok: true,
    count: requests.length,
    source,
    output: writtenPath,
    hint: writtenPath
      ? `Edit ${writtenPath} as needed, then run: brw script run ${writtenPath}`
      : 'Use --output <path> to save the script. Edit it, then run: brw script run <path>',
  };
}
